[package]
name = "ckb-jsonrpc-client"
version = "0.1.0"
authors = ["Boyu Yang <yangby@cryptape.com>"]
edition = "2018"

[dependencies]
ckb-jsonrpc-interfaces = { path = "../interfaces" }
jsonrpc-sdk-client = "0.1.2"
jsonrpc-sdk-prelude = "0.1.2"
futures = "~0.1"
tokio = "~0.1"
