[package]
name = "uckb-jsonrpc-client"
version = "0.1.0"
authors = ["Boyu Yang <yangby@cryptape.com>"]
edition = "2018"

[dependencies]
uckb-jsonrpc-interfaces = { path = "../interfaces" }
jsonrpc-sdk-client  = "=0.1.4"
jsonrpc-sdk-prelude = "=0.1.4"
futures = "~0.1"
url = "~1.7"
